# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  displayName: "NPM Install"
  inputs:
    script: 'npm install'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  displayName: "NPM Install Electron Packager"
  inputs:
    script: 'npm install -g electron-packager'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  displayName: "NPM Install Windows Store"
  inputs:
    script: 'npm install -g electron-windows-store'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  displayName: "NPM Test"
  inputs:
    script: 'npm test'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  displayName: "Package"
  inputs:
    script: 'electron-packager ./'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  displayName: "Store"
  inputs:
    script: 'electron-windows-store --input-directory .\Patchwork-win32-x64 --output-directory .\Patchwork-win32-x64-store'
    workingDirectory: '$(Build.SourcesDirectory)'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)\Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'